# https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
FROM node:slim

# Create app directory
WORKDIR /bot/

# Copy /bot/**
COPY . ./

# Install
RUN yarn

# Copy /src/**
COPY src ./

# Open 8080
EXPOSE 8080

# Start
CMD [ "yarn", "start" ]